// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace BookFast.Proxy.Models
{
    public partial class BookingRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the BookingRepresentation class.
        /// </summary>
        public BookingRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the BookingRepresentation class.
        /// </summary>
        public BookingRepresentation(string id = default(string), string accommodationId = default(string), string accommodationName = default(string), string facilityId = default(string), string facilityName = default(string), string streetAddress = default(string), DateTime? fromDate = default(DateTime?), DateTime? toDate = default(DateTime?))
        {
            Id = id;
            AccommodationId = accommodationId;
            AccommodationName = accommodationName;
            FacilityId = facilityId;
            FacilityName = facilityName;
            StreetAddress = streetAddress;
            FromDate = fromDate;
            ToDate = toDate;
        }

        /// <summary>
        /// Booking ID
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Accommodation ID
        /// </summary>
        [JsonProperty(PropertyName = "AccommodationId")]
        public string AccommodationId { get; set; }

        /// <summary>
        /// Accommodation name
        /// </summary>
        [JsonProperty(PropertyName = "AccommodationName")]
        public string AccommodationName { get; set; }

        /// <summary>
        /// Facility ID
        /// </summary>
        [JsonProperty(PropertyName = "FacilityId")]
        public string FacilityId { get; set; }

        /// <summary>
        /// Facility name
        /// </summary>
        [JsonProperty(PropertyName = "FacilityName")]
        public string FacilityName { get; set; }

        /// <summary>
        /// Facility street address
        /// </summary>
        [JsonProperty(PropertyName = "StreetAddress")]
        public string StreetAddress { get; set; }

        /// <summary>
        /// Booking start date
        /// </summary>
        [JsonProperty(PropertyName = "FromDate")]
        public DateTime? FromDate { get; set; }

        /// <summary>
        /// Booking end date
        /// </summary>
        [JsonProperty(PropertyName = "ToDate")]
        public DateTime? ToDate { get; set; }

    }
}
