// Code generated by Microsoft (R) AutoRest Code Generator 0.15.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace BookFast.Proxy.Models
{
    using System;
    using Newtonsoft.Json;

    public partial class FacilityRepresentation
    {
        /// <summary>
        /// Initializes a new instance of the FacilityRepresentation class.
        /// </summary>
        public FacilityRepresentation() { }

        /// <summary>
        /// Initializes a new instance of the FacilityRepresentation class.
        /// </summary>
        public FacilityRepresentation(Guid? id = default(Guid?), string name = default(string), string description = default(string), string streetAddress = default(string), double? longitude = default(double?), double? latitude = default(double?), int? accommodationCount = default(int?))
        {
            Id = id;
            Name = name;
            Description = description;
            StreetAddress = streetAddress;
            Longitude = longitude;
            Latitude = latitude;
            AccommodationCount = accommodationCount;
        }

        /// <summary>
        /// Facility ID
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Facility name
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Facility description
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// Facility street address
        /// </summary>
        [JsonProperty(PropertyName = "StreetAddress")]
        public string StreetAddress { get; set; }

        /// <summary>
        /// Latitude
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// Longitude
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

        /// <summary>
        /// Number of accommodations
        /// </summary>
        [JsonProperty(PropertyName = "AccommodationCount")]
        public int? AccommodationCount { get; set; }

    }
}
